### ISSUE TITLE
Error cloning cppwinrt submodule

### ISSUE THREAD

**Issue by jjhegedus** [coderox/DirectXCppWinRT#1]
Hi Johan, thanks for sharing this.  I've been trying to pull it down but I'm getting the following error cloning the submodule.  Any ideas on what might be going on here?

$ git clone --recursive git://github.com/coderox/DirectXCppWinRT.git
Cloning into 'DirectXCppWinRT'...
remote: Counting objects: 184, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 184 (delta 113), reused 184 (delta 113), pack-reused 0
Receiving objects: 100% (184/184), 65.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (113/113), done.
Checking connectivity... done.
Submodule 'cppwinrt' (git@github.com:Microsoft/cppwinrt.git) registered for path 'cppwinrt'
Cloning into 'C:/Projects/Git/coderox/DirectXCppWinRT/cppwinrt'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Microsoft/cppwinrt.git' into submodule path 'C:/Projects/Git/coderox/DirectXCppWinRT/cppwinrt' failed

**Comment by johanlindfors** [comment]
I'm not really certain what's causing this since it works just fine for me. Could you try the following instead:

git clone git://github.com/coderox/DirectXCppWinRT.git
cd DirectXCppWinRT
git submodule update --init --recursive

**Comment by jjhegedus** [comment]
Still no love Johan but you've given me another thing to learn about... git submodules.  I'll dig in and see what I can figure out.

By the way, I don't think you were a bad citizen sending your pull request.  I think you are engaging strongly with the team and the community.  In fact, you inspired me to send the cppwinrt crew a pull request of my own.  I've been working on converting the Holograpic DirectX sample.  If they decline the pull request, you can check it out in my fork of cppwinrt at https://github.com/jjhegedus/cppwinrt.  I created a new folder in the Samples called HolographicCube.  I converted from ppl to coroutines and replaced ComPtr with winrt::com_ptr so it might help with those hurdles if you're interested.  I plan to look through how you approached converting the DirectX sample to see how it compares to what I did with the holographic sample.

Thanks again,
Jeff

**Comment by johanlindfors** [comment]
Interesting, since apparently you have access to the original git repo of cppwinrt.

Regarding being a good citizen: https://hackernoon.com/being-a-good-open-source-citizen-9060d0ab9732

**Comment by johanlindfors** [comment]
No need to use cppwinrt as submodule since it is now published as a nuget package!
